"""add reservation and payment indexes

Revision ID: 4eb3c5d24f12
Revises: 9449db775958
Create Date: 2026-07-20 11:16:16.270841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb3c5d24f12'
down_revision = '9449db775958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payment_status_paid_at', ['status', 'paid_at'], unique=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('ix_reservation_customer_status_start', ['customer_id', 'status', 'start_time'], unique=False)
        batch_op.create_index('ix_reservation_room_status_end', ['room_id', 'status', 'end_time'], unique=False)
        batch_op.create_index('ix_reservation_room_status_start', ['room_id', 'status', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_reservation_room_status_start')
        batch_op.drop_index('ix_reservation_room_status_end')
        batch_op.drop_index('ix_reservation_customer_status_start')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_status_paid_at')




    # ### end Alembic commands ###
